export type FlowOverlayId = "off" | "front" | "floor" | "rear";

export const focusPoints = [
  {
    id: "front-wing",
    shortLabel: "Front wing",
    title: "Front wing + nose",
    summary: "This is where the car starts shaping airflow around the front tyres and into the floor.",
    note: "Front-facing camera with a tighter distance for nose and front-wing framing.",
    learnHref: "/learn/aero",
    learnLabel: "Open aero module",
    replayTitle: "Replay the front-end load story",
    replaySummary: "Use replay to watch turn-in, front grip, and how quickly the car settles into medium and high-speed direction changes.",
    orbit: "6deg 81deg 1.78m",
    target: "0m 0.24m 0m",
    flowOverlay: "front",
    hotspotPosition: "-0.35m 0.2m 2.15m",
    hotspotNormal: "0 0 1",
  },
  {
    id: "floor",
    shortLabel: "Floor",
    title: "Floor + diffuser channel",
    summary: "The biggest downforce story sits underneath the car, where the floor accelerates flow toward the diffuser.",
    note: "Higher angle to read the car planform and the underbody entry path.",
    learnHref: "/learn/aero",
    learnLabel: "Read the floor story",
    replayTitle: "Replay the underfloor balance",
    replaySummary: "Stay with the long, fast corners and watch whether the car looks planted under sustained load when the floor is doing most of the work.",
    orbit: "0deg 18deg 2.18m",
    target: "0m 0.18m 0m",
    flowOverlay: "floor",
    hotspotPosition: "0.05m 0.02m 0.55m",
    hotspotNormal: "0 1 0",
  },
  {
    id: "rear-wing",
    shortLabel: "Rear wing",
    title: "Rear wing + wake",
    summary: "Rear load and drag management live here, especially when you want to explain DRS or top-speed compromise.",
    note: "Rear-biased orbit for the exit flow and rear-wing assembly.",
    learnHref: "/learn/aero",
    learnLabel: "Follow rear aero",
    replayTitle: "Replay the drag-versus-stability tradeoff",
    replaySummary: "Watch DRS zones, top speed, and exit stability when rear load and drag are the engineering story you care about.",
    orbit: "186deg 78deg 1.82m",
    target: "0m 0.26m 0m",
    flowOverlay: "rear",
    hotspotPosition: "0.18m 0.58m -1.9m",
    hotspotNormal: "0 0.5 0.5",
  },
  {
    id: "brakes",
    shortLabel: "Brakes",
    title: "Brake ducts + brake energy",
    summary: "Cooling, brake balance, and harvesting all become easier to explain once you isolate the front-corner hardware.",
    note: "Side-biased camera that keeps the wheel corner and duct area readable.",
    learnHref: "/learn/braking",
    learnLabel: "Open braking module",
    replayTitle: "Replay the heavy braking zones",
    replaySummary: "Scrub the lap through the biggest braking events and compare brake percentage, minimum speed, and the release back into rotation.",
    orbit: "104deg 83deg 1.74m",
    target: "0m 0.22m 0m",
    flowOverlay: "off",
    hotspotPosition: "-0.55m 0.18m 1.5m",
    hotspotNormal: "-0.4 0 0.8",
  },
  {
    id: "tyres",
    shortLabel: "Tyres",
    title: "Tyres + contact patch",
    summary: "The tyre is still the last translator of every aero and braking decision into actual grip.",
    note: "Closer side view for wheelbase, tyre shape, and stance.",
    learnHref: "/learn/tyres",
    learnLabel: "Open tyre module",
    replayTitle: "Replay the tyre story",
    replaySummary: "Watch pace loss, traction on exit, and how the car changes character over a run when the tyre window starts to move.",
    orbit: "96deg 84deg 1.6m",
    target: "0m 0.2m 0m",
    flowOverlay: "off",
    hotspotPosition: "0.92m 0.14m -0.95m",
    hotspotNormal: "0.6 0 0.4",
  },
] as const;

export type FocusPoint = (typeof focusPoints)[number];
export type FocusPointId = FocusPoint["id"];

export function getFocusPoint(id: string | null | undefined) {
  return focusPoints.find((point) => point.id === id) ?? null;
}
